***PANDAS***

---

In [5]:
import pandas as pd
df=pd.read_csv("/content/drive/MyDrive/International_T20_Data.csv")
#display first 5 rows
df.head()

,innings,meta.data_version,meta.created,meta.revision,info.dates,info.gender,info.match_type,info.outcome.by.wickets,info.outcome.winner,info.overs,...,info.outcome.by.runs,info.match_type_number,info.neutral_venue,info.outcome.method,info.outcome.result,info.outcome.eliminator,info.supersubs.New Zealand,info.supersubs.South Africa,info.bowl_out,info.outcome.bowl_out
1412,"[{'1st innings': {'team': 'Sri Lanka', 'delive...",0.9,2016-03-05,2,"[datetime.date(2016, 3, 4)]",male,T20,6.0,Pakistan,20,...,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1413,"[{'1st innings': {'team': 'Bangladesh', 'deliv...",0.9,2016-03-08,1,"[datetime.date(2016, 3, 6)]",male,T20,8.0,India,20,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1414,"[{'1st innings': {'team': 'Netherlands', 'deli...",0.9,2016-02-03,1,"[datetime.date(2016, 2, 3)]",male,T20,NaN,Netherlands,20,...,84.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1415,"[{'1st innings': {'team': 'Australia', 'delive...",0.9,2016-09-12,1,"[datetime.date(2016, 9, 6)]",male,T20,NaN,Australia,20,...,85.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1416,"[{'1st innings': {'team': 'Sri Lanka', 'delive...",0.9,2016-09-12,1,"[datetime.date(2016, 9, 9)]",male,T20,4.0,Australia,20,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
#display last 5 rows
df.tail()

,innings,meta.data_version,meta.created,meta.revision,info.dates,info.gender,info.match_type,info.outcome.by.wickets,info.outcome.winner,info.overs,...,info.outcome.by.runs,info.match_type_number,info.neutral_venue,info.outcome.method,info.outcome.result,info.outcome.eliminator,info.supersubs.New Zealand,info.supersubs.South Africa,info.bowl_out,info.outcome.bowl_out
1412,"[{'1st innings': {'team': 'Sri Lanka', 'delive...",0.9,2016-03-05,2,"[datetime.date(2016, 3, 4)]",male,T20,6.0,Pakistan,20,...,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1413,"[{'1st innings': {'team': 'Bangladesh', 'deliv...",0.9,2016-03-08,1,"[datetime.date(2016, 3, 6)]",male,T20,8.0,India,20,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1414,"[{'1st innings': {'team': 'Netherlands', 'deli...",0.9,2016-02-03,1,"[datetime.date(2016, 2, 3)]",male,T20,NaN,Netherlands,20,...,84.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1415,"[{'1st innings': {'team': 'Australia', 'delive...",0.9,2016-09-12,1,"[datetime.date(2016, 9, 6)]",male,T20,NaN,Australia,20,...,85.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1416,"[{'1st innings': {'team': 'Sri Lanka', 'delive...",0.9,2016-09-12,1,"[datetime.date(2016, 9, 9)]",male,T20,4.0,Australia,20,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
#Shape(rows,columns)
df.shape

(1417, 27)

In [8]:
#Column names
df.columns

Index(['innings', 'meta.data_version', 'meta.created', 'meta.revision',
       'info.dates', 'info.gender', 'info.match_type',
       'info.outcome.by.wickets', 'info.outcome.winner', 'info.overs',
       'info.player_of_match', 'info.teams', 'info.toss.decision',
       'info.toss.winner', 'info.umpires', 'info.venue', 'info.city',
       'info.outcome.by.runs', 'info.match_type_number', 'info.neutral_venue',
       'info.outcome.method', 'info.outcome.result', 'info.outcome.eliminator',
       'info.supersubs.New Zealand', 'info.supersubs.South Africa',
       'info.bowl_out', 'info.outcome.bowl_out'],
      dtype='object')

In [9]:
#data type & info
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1417 entries, 0 to 1416
Data columns (total 27 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   innings                      1417 non-null   object
 1   meta.data_version            1417 non-null   float64
 2   meta.created                 1417 non-null   object
 3   meta.revision                1417 non-null   int64
 4   info.dates                   1417 non-null   object
 5   info.gender                  1417 non-null   object
 6   info.match_type              1417 non-null   object
 7   info.outcome.by.wickets      651 non-null    float64
 8   info.outcome.winner          1372 non-null   object
 9   info.overs                   1417 non-null   int64
 10  info.player_of_match         1255 non-null   object
 11  info.teams                   1417 non-null   object
 12  info.toss.decision           1417 non-null   object
 13  info.toss.winner             1417 non-null   object
 14  info.umpires                 1395 non-null   object
 15  info.venue                   1417 non-null   object
 16  info.city                    1228 non-null   object
 17  info.outcome.by.runs         721 non-null    float64
 18  info.match_type_number       684 non-null    float64
 19  info.neutral_venue           328 non-null    float64
 20  info.outcome.method          51 non-null     object
 21  info.outcome.result          45 non-null     object
 22  info.outcome.eliminator      16 non-null     object
 23  info.supersubs.New Zealand   1 non-null      object
 24  info.supersubs.South Africa  1 non-null      object
 25  info.bowl_out                2 non-null      object
 26  info.outcome.bowl_out        2 non-null      object
dtypes: float64(5), int64(2), object(20)
memory usage: 299.0+ KB

In [10]:
#check missing value
df.isnull().sum()

innings                           0
meta.data_version                 0
meta.created                      0
meta.revision                     0
info.dates                        0
info.gender                       0
info.match_type                   0
info.outcome.by.wickets         766
info.outcome.winner              45
info.overs                        0
info.player_of_match            162
info.teams                        0
info.toss.decision                0
info.toss.winner                  0
info.umpires                     22
info.venue                        0
info.city                       189
info.outcome.by.runs            696
info.match_type_number          733
info.neutral_venue             1089
info.outcome.method            1366
info.outcome.result            1372
info.outcome.eliminator        1401
info.supersubs.New Zealand     1416
info.supersubs.South Africa    1416
info.bowl_out                  1415
info.outcome.bowl_out          1415
dtype: int64

In [11]:
#statistics
df.describe()

,meta.data_version,meta.revision,info.outcome.by.wickets,info.overs,info.outcome.by.runs,info.match_type_number,info.neutral_venue
count,1.417000e+03,1417.000000,651.000000,1417.000000,721.000000,684.000000,328.0
mean,9.000000e-01,1.370501,6.476190,20.063514,39.088766,748.774854,1.0
std,5.108829e-15,0.575198,1.987802,1.379399,33.385757,190.050264,0.0
min,9.000000e-01,1.000000,1.000000,20.000000,1.000000,380.000000,1.0
25%,9.000000e-01,1.000000,5.000000,20.000000,13.000000,627.000000,1.0
50%,9.000000e-01,1.000000,7.000000,20.000000,30.000000,746.500000,1.0
75%,9.000000e-01,2.000000,8.000000,20.000000,56.000000,883.250000,1.0
max,9.000000e-01,5.000000,10.000000,50.000000,249.000000,1104.000000,1.0

In [17]:
df['info.city']
#matches in specific city
df[df['info.city']=='Dubai']

,innings,meta.data_version,meta.created,meta.revision,info.dates,info.gender,info.match_type,info.outcome.by.wickets,info.outcome.winner,info.overs,...,info.outcome.by.runs,info.match_type_number,info.neutral_venue,info.outcome.method,info.outcome.result,info.outcome.eliminator,info.supersubs.New Zealand,info.supersubs.South Africa,info.bowl_out,info.outcome.bowl_out
32,"[{'1st innings': {'team': 'Afghanistan', 'deli...",0.9,2016-12-17,1,"[datetime.date(2016, 12, 14)]",male,T20,NaN,Afghanistan,20,...,11.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,"[{'1st innings': {'team': 'Afghanistan', 'deli...",0.9,2016-12-19,1,"[datetime.date(2016, 12, 18)]",male,T20,NaN,Afghanistan,20,...,44.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
306,[{'1st innings': {'team': 'United Arab Emirate...,0.9,2020-03-29,1,['2019-01-31'],male,T20,NaN,United Arab Emirates,20,...,21.0,730.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
307,[{'1st innings': {'team': 'United Arab Emirate...,0.9,2020-03-29,1,['2019-02-01'],male,T20,4.0,Nepal,20,...,NaN,731.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
308,"[{'1st innings': {'team': 'Nepal', 'deliveries...",0.9,2020-03-30,1,['2019-02-03'],male,T20,NaN,Nepal,20,...,14.0,733.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
376,[{'1st innings': {'team': 'United States of Am...,0.9,2020-01-02,1,['2019-03-15'],male,T20,NaN,NaN,20,...,NaN,753.0,NaN,NaN,no result,NaN,NaN,NaN,NaN,NaN
377,[{'1st innings': {'team': 'United Arab Emirate...,0.9,2020-01-02,1,['2019-03-16'],male,T20,NaN,United Arab Emirates,20,...,24.0,754.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
595,"[{'1st innings': {'team': 'Singapore', 'delive...",0.9,2019-10-18,1,['2019-10-18'],male,T20,NaN,Singapore,20,...,2.0,935.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
597,"[{'1st innings': {'team': 'Netherlands', 'deli...",0.9,2019-10-19,1,['2019-10-18'],male,T20,NaN,Netherlands,20,...,30.0,938.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
599,"[{'1st innings': {'team': 'Bermuda', 'deliveri...",0.9,2019-10-20,1,['2019-10-19'],male,T20,10.0,Papua New Guinea,20,...,NaN,940.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
601,"[{'1st innings': {'team': 'Netherlands', 'deli...",0.9,2019-10-21,1,['2019-10-19'],male,T20,NaN,Netherlands,20,...,44.0,941.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
602,"[{'1st innings': {'team': 'Scotland', 'deliver...",0.9,2019-10-22,1,['2019-10-19'],male,T20,NaN,Scotland,20,...,31.0,942.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
604,"[{'1st innings': {'team': 'Papua New Guinea', ...",0.9,2019-10-23,1,['2019-10-20'],male,T20,NaN,Papua New Guinea,20,...,81.0,945.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
606,"[{'1st innings': {'team': 'Bermuda', 'deliveri...",0.9,2019-10-23,1,['2019-10-20'],male,T20,5.0,Singapore,20,...,NaN,947.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
608,"[{'1st innings': {'team': 'Scotland', 'deliver...",0.9,2019-10-23,1,['2019-10-21'],male,T20,NaN,Scotland,20,...,4.0,949.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
611,"[{'1st innings': {'team': 'Kenya', 'deliveries...",0.9,2019-10-23,1,['2019-10-21'],male,T20,NaN,Kenya,20,...,45.0,952.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
613,"[{'1st innings': {'team': 'Namibia', 'deliveri...",0.9,2019-10-24,1,['2019-10-22'],male,T20,NaN,Namibia,20,...,24.0,954.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
614,"[{'1st innings': {'team': 'Singapore', 'delive...",0.9,2019-10-24,1,['2019-10-22'],male,T20,5.0,Netherlands,20,...,NaN,956.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
616,"[{'1st innings': {'team': 'Bermuda', 'deliveri...",0.9,2019-10-24,1,['2019-10-23'],male,T20,6.0,Namibia,20,...,NaN,958.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
618,"[{'1st innings': {'team': 'Singapore', 'delive...",0.9,2019-10-24,1,['2019-10-23'],male,T20,7.0,Kenya,20,...,NaN,960.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
621,"[{'1st innings': {'team': 'Netherlands', 'deli...",0.9,2019-10-24,1,['2019-10-24'],male,T20,5.0,Papua New Guinea,20,...,NaN,963.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
624,"[{'1st innings': {'team': 'Scotland', 'deliver...",0.9,2019-10-25,1,['2019-10-24'],male,T20,NaN,Scotland,20,...,46.0,966.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
625,"[{'1st innings': {'team': 'Papua New Guinea', ...",0.9,2019-10-26,1,['2019-10-25'],male,T20,NaN,Papua New Guinea,20,...,43.0,967.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
627,"[{'1st innings': {'team': 'Namibia', 'deliveri...",0.9,2019-10-26,1,['2019-10-25'],male,T20,NaN,Namibia,20,...,87.0,969.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
630,"[{'1st innings': {'team': 'Netherlands', 'deli...",0.9,2019-10-26,1,['2019-10-26'],male,T20,NaN,Netherlands,20,...,92.0,974.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
631,"[{'1st innings': {'team': 'Namibia', 'deliveri...",0.9,2019-10-27,1,['2019-10-26'],male,T20,NaN,Namibia,20,...,87.0,975.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
632,"[{'1st innings': {'team': 'Papua New Guinea', ...",0.9,2019-10-28,1,['2019-10-27'],male,T20,NaN,Papua New Guinea,20,...,45.0,979.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
635,"[{'1st innings': {'team': 'Scotland', 'deliver...",0.9,2019-10-28,1,['2019-10-27'],male,T20,4.0,Netherlands,20,...,NaN,983.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
637,[{'1st innings': {'team': 'United Arab Emirate...,0.9,2019-10-29,1,['2019-10-29'],male,T20,8.0,Netherlands,20,...,NaN,986.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
638,"[{'1st innings': {'team': 'Namibia', 'deliveri...",0.9,2019-10-30,1,['2019-10-29'],male,T20,NaN,Namibia,20,...,54.0,987.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
639,"[{'1st innings': {'team': 'Scotland', 'deliver...",0.9,2019-10-30,1,['2019-10-30'],male,T20,NaN,Scotland,20,...,90.0,989.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
640,"[{'1st innings': {'team': 'Oman', 'deliveries'...",0.9,2019-10-30,1,['2019-10-30'],male,T20,NaN,Oman,20,...,12.0,990.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
641,"[{'1st innings': {'team': 'Oman', 'deliveries'...",0.9,2019-10-31,1,['2019-10-31'],male,T20,5.0,Scotland,20,...,NaN,991.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
642,"[{'1st innings': {'team': 'Netherlands', 'deli...",0.9,2019-11-01,1,['2019-11-01'],male,T20,NaN,Netherlands,20,...,21.0,994.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
643,"[{'1st innings': {'team': 'Papua New Guinea', ...",0.9,2019-11-06,1,['2019-11-01'],male,T20,NaN,Papua New Guinea,20,...,18.0,995.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
644,"[{'1st innings': {'team': 'Ireland', 'deliveri...",0.9,2019-11-06,1,['2019-11-02'],male,T20,NaN,Ireland,20,...,27.0,996.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
645,"[{'1st innings': {'team': 'Papua New Guinea', ...",0.9,2019-11-06,1,['2019-11-02'],male,T20,7.0,Netherlands,20,...,NaN,997.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1014,"[{'1st innings': {'team': 'Afghanistan', 'deli...",0.9,2012-12-29,3,"[datetime.date(2012, 3, 18)]",male,T20,NaN,Afghanistan,20,...,41.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1066,"[{'1st innings': {'team': 'Kenya', 'deliveries...",0.9,2013-03-25,1,"[datetime.date(2013, 3, 15)]",male,T20,5.0,Canada,20,...,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1067,"[{'1st innings': {'team': 'Kenya', 'deliveries...",0.9,2013-03-25,1,"[datetime.date(2013, 3, 16)]",male,T20,NaN,Kenya,20,...,21.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1112,"[{'1st innings': {'team': 'Kenya', 'deliveries...",0.9,2013-12-19,1,"[datetime.date(2013, 11, 19)]",male,T20,NaN,Kenya,20,...,92.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1113,"[{'1st innings': {'team': 'Scotland', 'deliver...",0.9,2013-12-18,2,"[datetime.date(2013, 11, 22)]",male,T20,NaN,Scotland,20,...,15.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1114,"[{'1st innings': {'team': 'Netherlands', 'deli...",0.9,2013-12-18,2,"[datetime.date(2013, 11, 23)]",male,T20,NaN,Netherlands,20,...,29.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1396,[{'1st innings': {'team': 'United Arab Emirate...,0.9,2016-02-08,1,"[datetime.date(2016, 2, 4)]",male,T20,NaN,United Arab Emirates,20,...,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1414,"[{'1st innings': {'team': 'Netherlands', 'deli...",0.9,2016-02-03,1,"[datetime.date(2016, 2, 3)]",male,T20,NaN,Netherlands,20,...,84.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
#count matches per city
df['info.city'].value_counts()

info.city
Colombo         57
Abu Dhabi       50
Dubai           45
Mirpur          39
Kuala Lumpur    38
                ..
Sharjah          1
Ahmedabad        1
Mohali           1
Grenada          1
Dharmasala       1
Name: count, Length: 144, dtype: int64

In [20]:
#Sort by overs
df['info.overs']
df.sort_values(by='info.overs',ascending=False)

,innings,meta.data_version,meta.created,meta.revision,info.dates,info.gender,info.match_type,info.outcome.by.wickets,info.outcome.winner,info.overs,...,info.outcome.by.runs,info.match_type_number,info.neutral_venue,info.outcome.method,info.outcome.result,info.outcome.eliminator,info.supersubs.New Zealand,info.supersubs.South Africa,info.bowl_out,info.outcome.bowl_out
1280,"[{'1st innings': {'team': 'New Zealand', 'deli...",0.9,2015-08-10,1,"[datetime.date(2015, 8, 9)]",male,T20,NaN,New Zealand,50,...,80.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
692,"[{'1st innings': {'team': 'West Indies', 'deli...",0.9,2020-03-05,1,['2020-03-04'],male,T20,NaN,West Indies,50,...,25.0,1075.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
693,"[{'1st innings': {'team': 'Sri Lanka', 'delive...",0.9,2020-03-06,1,['2020-03-06'],male,T20,7.0,West Indies,50,...,NaN,1078.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
950,"[{'1st innings': {'team': 'England', 'deliveri...",0.9,2014-05-25,2,"[datetime.date(2012, 2, 22)]",female,T20,NaN,England,20,...,10.0,NaN,NaN,D/L,NaN,NaN,NaN,NaN,NaN,NaN
948,"[{'1st innings': {'team': 'New Zealand', 'deli...",0.9,2014-05-25,2,"[datetime.date(2012, 2, 17)]",female,T20,6.0,England,20,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
467,"[{'1st innings': {'team': 'New Zealand', 'deli...",0.9,2019-11-01,1,['2019-11-01'],male,T20,7.0,England,20,...,NaN,992.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
466,"[{'1st innings': {'team': 'India', 'deliveries...",0.9,2019-12-18,1,['2019-12-11'],male,T20,NaN,India,20,...,67.0,1024.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
465,"[{'1st innings': {'team': 'India', 'deliveries...",0.9,2019-12-18,1,['2019-12-08'],male,T20,8.0,West Indies,20,...,NaN,1022.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
464,"[{'1st innings': {'team': 'West Indies', 'deli...",0.9,2019-12-18,1,['2019-12-06'],male,T20,6.0,India,20,...,NaN,1020.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
475,"[{'1st innings': {'team': 'India', 'deliveries...",0.9,2020-02-09,1,['2020-01-31'],male,T20,NaN,NaN,20,...,NaN,1036.0,NaN,NaN,tie,India,NaN,NaN,NaN,NaN